### ISSUE TITLE
Restore clean pom and build

### ISSUE THREAD

**Issue by oliviercailloux** [sebastienbourg/J-Confs#23]
Je m’aperçois à l’instant de deux problèmes bloquants (probablement liés), à résoudre en très grande priorité.
- Le projet ne compile plus
- Maven avertit concernant des bizarreries dans le POM, et effectivement, il est rempli de directives inutiles, dangereuses ou incorrectes, qui fragilisent le projet et le rendront difficile à maintenir et à faire évoluer.

Je pense avoir accepté par erreur, avec la PR d’import de LocationIq, des modifications incorrectes du POM.

Je vous prie de procéder comme suit :
- restaurer (directement dans la branche master) le POM tel qu’il était au début de cette année (dans le commit 4fcd43fcba3eb8fdc3f8834c3100f63a9ca59436) ;
- ouvrir une PR pour proposer une modiication du POM saine et claire, et qui restaure la compilation du projet, et me demander une review quand vous êtes prêts. Je la traiterai en priorité.

**Comment by sebastienbourg** [comment]
Bonsoir Monsieur,

Nous n'observons pas d'erreur de compilation du projet présent sur la branche master. En cas d'erreur il suffit de faire Maven -> Update Project.
Cependant nous avons constaté avec "mvn compile" deux warnings que nous avons corrigés. Un warning provenait en effet de notre PR précédente mais pas l'autre.
Le POM a été restauré dans master selon le commit 4fcd43fcba3eb8fdc3f8834c3100f63a9ca59436
**Veuillez noter que le projet ne compile pas actuellement à cause de cette restauration**

La PR #24 vous a été adressée afin de prendre en compte le POM intégrant les dépendances de locationIQ et avec les doublons supprimés.
Une fois accepté nous modifieront le pom dans toutes nos autres branches et re procéderons aux PR pour l'itération 2 de java.

**Comment by oliviercailloux** [comment]
Avez-vous testé avec Maven en ligne de commande (avec le POM comme avant restauration) ?

**Comment by sebastienbourg** [comment]
Oui avec la coommande "mvn compile" comme indiqué au dessus. Le build était success.

**Comment by oliviercailloux** [comment]
Je voulais dire, avez-vous essayé `mvn test` en ligne de commande ?

**Comment by sebastienbourg** [comment]
Je viens de tester sur une branche (It2OurLocationClass) contenant le pom avant restauration et le build fini en success. 
En effet sur master cela ne fonctionne pas à cause de tests et de classes présents dans les packages src/main/java/LocationIq et src/test/java/com/locationiq/client/* , ces tests et classes seront supprimées dans le cadre de la revue de l'architecture de l'api (voir pull request #20 )
